# AI Team extension: shared helpers for handoff spec sync (PowerShell)

function Find-HandoffSpecProjectRoot {
    param([string]$StartDir)
    $current = (Resolve-Path $StartDir).Path
    while ($true) {
        foreach ($marker in @('.specify', '.git')) {
            if (Test-Path (Join-Path $current $marker)) { return $current }
        }
        $parent = Split-Path $current -Parent
        if ($parent -eq $current) { return $null }
        $current = $parent
    }
}

function Get-HandoffOverrideFileName {
    param([string]$RepoRoot)
    $name = 'spec.override.md'
    $config = Join-Path $RepoRoot '.specify/extensions/ai-team/ai-team-config.yml'
    if (Test-Path $config) {
        $line = Get-Content -LiteralPath $config | Where-Object { $_ -match 'private_handoff_override_file:' } | Select-Object -First 1
        if ($line -match 'private_handoff_override_file:\s*(\S+)') {
            $name = $Matches[1].Trim('"', "'")
        }
    }
    return $name
}

function Resolve-EffectiveSpecPath {
    param(
        [string]$FeatureDir,
        [string]$OverrideName = 'spec.override.md'
    )
    $override = Join-Path $FeatureDir $OverrideName
    if (Test-Path $override -PathType Leaf) { return $override }
    return Join-Path $FeatureDir 'spec.md'
}

function Get-HandoffUrlFromText {
    param([string]$Text)
    if ([string]::IsNullOrWhiteSpace($Text)) { return $null }
    foreach ($key in @('handoff_requirement_url', 'published_requirement_url')) {
        if ($Text -match "${key}\s*=\s*(https://[^\s`"'>]+)") { return $Matches[1].TrimEnd('/') }
        if ($Text -match "${key}:\s*(https://[^\s`"'#]+)") { return $Matches[1].TrimEnd('/') }
    }
    return $null
}

function Get-HandoffRequirementUrl {
    param(
        [string]$RepoRoot,
        [string]$ArgsText,
        [hashtable]$Paths
    )
    foreach ($envName in @('HANDOFF_REQUIREMENT_URL', 'PUBLISHED_REQUIREMENT_URL')) {
        $val = [Environment]::GetEnvironmentVariable($envName)
        if ($val -match '^https://') { return $val.TrimEnd('/') }
    }
    $fromArgs = Get-HandoffUrlFromText -Text $ArgsText
    if ($fromArgs) { return $fromArgs }

    $tasksRoot = Join-Path $RepoRoot '.specify/ai-team/tasks'
    $taskId = $null
    if ($ArgsText -match 'task_id=([^\s`"'>]+)') { $taskId = $Matches[1] }
    if ($taskId) {
        $ctx = Join-Path $tasksRoot "$taskId/task-context.yml"
        if (Test-Path $ctx) {
            $url = Get-HandoffUrlFromText -Text (Get-Content -LiteralPath $ctx -Raw)
            if ($url) { return $url }
        }
    }
    if (Test-Path $tasksRoot) {
        Get-ChildItem -Path $tasksRoot -Directory | ForEach-Object {
            $ctx = Join-Path $_.FullName 'task-context.yml'
            if (Test-Path $ctx) {
                $url = Get-HandoffUrlFromText -Text (Get-Content -LiteralPath $ctx -Raw)
                if ($url) { return $url }
            }
        }
    }
    if ($Paths.FEATURE_SPEC -and (Test-Path $Paths.FEATURE_SPEC)) {
        $head = (Get-Content -LiteralPath $Paths.FEATURE_SPEC -TotalCount 40) -join "`n"
        $url = Get-HandoffUrlFromText -Text $head
        if ($url) { return $url }
    }
    return $null
}

function Ensure-GitignorePattern {
    param(
        [string]$RepoRoot,
        [string]$Pattern = '**/spec.override.md'
    )
    $gitignore = Join-Path $RepoRoot '.gitignore'
    if ((Test-Path $gitignore) -and (Select-String -LiteralPath $gitignore -Pattern ([regex]::Escape($Pattern)) -Quiet)) {
        return
    }
    Add-Content -LiteralPath $gitignore -Value @("", "# Spec Kit AI Team remote handoff cache (auto-generated)", $Pattern)
}

function Test-SpecIsPointerOnly {
    param([string]$SpecFile)
    if (-not (Test-Path $SpecFile)) { return $false }
    $text = Get-Content -LiteralPath $SpecFile -Raw
    return ($text -match 'spec_source:\s*remote') -or ($text -match 'Remote Reference')
}

function Write-SpecPointer {
    param(
        [string]$SpecFile,
        [string]$Url
    )
    $dir = Split-Path $SpecFile -Parent
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
    $content = @"
---
handoff_requirement_url: $Url
spec_source: remote
---

# Feature Specification (Remote Reference)

**Handoff Requirement URL**: $Url

**Local cache**: ``spec.override.md`` (gitignored, generated by ``speckit.ai-team.handoff-spec-sync``)

> Do not edit this file for full requirement content. Re-run handoff sync or update the remote source.
"@
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($SpecFile, $content, $utf8NoBom)
}

function Get-RemoteRequirementContent {
    param([string]$Url)
    if (Get-Command curl.exe -ErrorAction SilentlyContinue) {
        return (curl.exe -fsSL $Url)
    }
    return (Invoke-WebRequest -Uri $Url -UseBasicParsing).Content
}

function Write-MergedOverride {
    param(
        [string]$OverrideFile,
        [string]$Url,
        [string]$SpecFile,
        [string]$FetchedContent
    )
    $timestamp = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('# Effective Feature Specification (AI Team Handoff)')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("**Source URL**: $Url")
    [void]$sb.AppendLine("**Generated**: $timestamp")
    [void]$sb.AppendLine('**Public baseline**: `spec.md` (preserved unchanged)')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('---')
    [void]$sb.AppendLine('')
    if ((Test-Path $SpecFile) -and -not (Test-SpecIsPointerOnly -SpecFile $SpecFile)) {
        [void]$sb.AppendLine('## Public baseline (from spec.md)')
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine((Get-Content -LiteralPath $SpecFile -Raw))
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('---')
        [void]$sb.AppendLine('')
    }
    [void]$sb.AppendLine('## Handoff requirement (fetched)')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine($FetchedContent)
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($OverrideFile, $sb.ToString(), $utf8NoBom)
}

function Write-HandoffSpecJson {
    param(
        [bool]$Skipped,
        [string]$FeatureDir,
        [string]$FeatureSpec,
        [string]$EffectiveSpec,
        [string]$HandoffUrl = '',
        [bool]$SpecBootstrapped = $false
    )
    [PSCustomObject]@{
        SKIPPED = $Skipped
        FEATURE_DIR = $FeatureDir
        FEATURE_SPEC = $FeatureSpec
        EFFECTIVE_SPEC = $EffectiveSpec
        HANDOFF_REQUIREMENT_URL = $HandoffUrl
        SPEC_BOOTSTRAPPED = $SpecBootstrapped
    } | ConvertTo-Json -Compress
}
