#!/usr/bin/env bash
set -euo pipefail

# create-github-release.sh
# Create a GitHub release with all InfraKit template zip files
# Usage: create-github-release.sh <version>

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <version>" >&2
  exit 1
fi

VERSION="$1"

# Remove 'v' prefix from version for release title
VERSION_NO_V=${VERSION#v}

# Discover all release packages generated by create-release-packages.sh
mapfile -t ZIP_FILES < <(find .genreleases -maxdepth 1 -name "infrakit-template-*-${VERSION}.zip" | sort)

if [[ ${#ZIP_FILES[@]} -eq 0 ]]; then
  echo "Error: No release packages found in .genreleases/ for version $VERSION" >&2
  exit 1
fi

gh release create "$VERSION" "${ZIP_FILES[@]}" \
  --title "InfraKit Templates - $VERSION_NO_V" \
  --notes-file release_notes.md
