/**
 * Project Configuration for MCP Server
 *
 * This file is generated by /speckit.mcp and customized for your project.
 * Modify the services, commands, and settings to match your stack.
 */

export interface ServiceConfig {
  name: string;
  command: string;
  cwd?: string;
  env?: Record<string, string>;
  healthCheck?: {
    url: string;
    expectedStatus?: number;
    timeout?: number;
  };
  dependsOn?: string[];
  logFile?: string;
}

export interface ProjectConfig {
  name: string;
  rootDir: string;
  services: ServiceConfig[];
  docker?: {
    composeFile?: string;
    services?: string[];
  };
  browser?: {
    baseUrl: string;
    headless?: boolean;
  };
  api?: {
    baseUrl: string;
    defaultHeaders?: Record<string, string>;
  };
}

// {{CONFIG_PLACEHOLDER}}
// This will be replaced by /speckit.mcp with actual project configuration

export const config: ProjectConfig = {
  name: "{{PROJECT_NAME}}",
  rootDir: "{{PROJECT_ROOT}}",

  services: [
    // Example backend service (Java/Spring)
    // {
    //   name: "backend",
    //   command: "./mvnw spring-boot:run",
    //   cwd: "backend",
    //   healthCheck: {
    //     url: "http://localhost:8080/actuator/health",
    //     expectedStatus: 200,
    //     timeout: 60000
    //   }
    // },

    // Example frontend service (Node/Vite)
    // {
    //   name: "frontend",
    //   command: "npm run dev",
    //   cwd: "frontend",
    //   healthCheck: {
    //     url: "http://localhost:5173",
    //     expectedStatus: 200,
    //     timeout: 30000
    //   },
    //   dependsOn: ["backend"]
    // },

    // Example Node.js service
    // {
    //   name: "api",
    //   command: "npm run start:dev",
    //   cwd: "api",
    //   env: { "NODE_ENV": "development" },
    //   healthCheck: {
    //     url: "http://localhost:3000/health",
    //     expectedStatus: 200
    //   }
    // }
  ],

  docker: {
    composeFile: "docker-compose.yml",
    services: ["db", "redis", "rabbitmq"]
  },

  browser: {
    baseUrl: "http://localhost:5173",
    headless: false
  },

  api: {
    baseUrl: "http://localhost:8080/api",
    defaultHeaders: {
      "Content-Type": "application/json"
    }
  }
};
